name = "mein-blog-frontend-v2"
compatibility_date = "2025-06-13"
pages_build_output_dir = ".vercel/output/static"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]  
compatibility_flags = ["nodejs_compat"]